---
banned-commands:
- tp
- warp
- tpa
- spawn
- hub
- kill
- suicide

StaffPlayer: ["ItsNotkungZ", "FamousNewky", "ninezy8562", "NotkungX"]

version: 1.2.0
enable-multiworld-chat: false
groups:
  Guest:
    chat: '&f[§aMember§f] &a {display_name} &7> &f{msg}'
    nametag: '&f[§aMember§f] &f{display_name}'
    worlds: []
  Admin:
    chat: '&f[§cAdmin§f] &6 {display_name} &d>>&b {msg}'
    nametag: '&f[§cAdmin§f] &6{display_name}'
    worlds: []
  Owner:
    chat: '&f[§6Owner§f] &b{display_name} &c>&6> &b{msg}'
    nametag: '&f[§6Owner§f] &b{display_name}'
    worlds: []
  OP:
    chat: '&a[OP] &5{fac_rank}{fac_name}&b {prefix}{display_name}{suffix} &c>&6> &f{msg}'
    nametag: '&a[OP] &c{fac_rank}{fac_name} &b{display_name}'
    worlds: []
  VIP:
    nametag: '§f[§6VIP§f] §e{display_name}'
    chat: '§f[§6VIP§f] §e{display_name} §6>§e> §e{msg}'
    worlds: []
  Superv:
    nametag: '§f[§6VIP§a+§f] §6{display_name}'
    chat: '§f[§6VIP§a+§f] §6{display_name} §b>§6> §b{msg}'
    worlds: []

...

